export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const GET_CHANGE_LIST = 'header/GET_CHANGE_LIST'
export const MOUSEOUT = 'header/MOUSEOUT'
export const MOUSEENTRY = 'header/MOUSEENTRY'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'
